# Generated by Django 4.0.6 on 2022-08-31 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_item_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='deadline',
            field=models.CharField(max_length=30),
        ),
    ]
