# Generated by Django 4.0.6 on 2022-08-31 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_item_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.TextField(max_length=20),
        ),
    ]
