# Generated by Django 4.0.6 on 2022-09-03 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_item_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='created',
        ),
        migrations.RemoveField(
            model_name='item',
            name='owner',
        ),
    ]
