# Generated by Django 4.0.6 on 2022-10-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_item_created_item_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='created',
        ),
        migrations.AlterField(
            model_name='item',
            name='deadline',
            field=models.DateField(),
        ),
    ]
