# Generated by Django 4.0.6 on 2022-10-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_item_created_alter_item_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='deadline',
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
