# Generated by Django 4.0.6 on 2022-09-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_roomitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='make_priority',
            field=models.BooleanField(default=False),
        ),
    ]
