# Generated by Django 4.0.6 on 2022-10-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_item_deadline_alter_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
